dataset:
  # NMNIST', 'PilotNet', ''
  name: 'PilotNet'
  event_representation: 'histogram'  # ['histogram', 'event_queue']
  pilotnet:
    dataset_path: "/home/ysekikawa/data/nvidia_drive/"
    object_classes: 'all'
    height: 66
    width: 200
    nr_events_window: -1
    proc_rate: 10

dir:
  log: '../log/'
model:
  model_name: 'dss_exp'
optim:
  batch_size: 64
  init_lr: 0.001
  n_epoch: 1000
  # Set to "steps: ~" if no scheduler is needed
  lr_scheduler_config: -1
  factor_lr: 0.5
checkpoint:                            
  resume_training: False
  resume_file:
  # resume_file: '/home/ysekikawa/mnt/Projects/GDK/src/rpg_asynet/log/data_PilotNet_model_dss_exp_kernel_cnn_eta_0_nps_1/checkpoints/model_step_91.pth'
  use_pretrained: False
  pretrained_dense_vgg: ''
  pretrained_sparse_vgg: ''
hardware:
  num_cpu_workers: 0 # {-1: auto, 0: main thread, >0: ...}
  gpu_device: 0  # [0 or 'cpu']
  pin_memory: True

dss:
  # ['conv_nan', 'lc_nan', 'lrlc_nan', 'conv_conv', 'lrlc_lrlc', 'lc_lc', 'red']
  kernel_mode: 'conv_conv'

  # W/ DSS
  expantion_ratio: 1
  DSS_weight: 2e-1
  DSS_weight_step: 4e0
  dss_criteria: 0.02


  q_threshold: 1e-1 
  spatial_rank: 5
  bias_pd: False
  channel_wise_th: True
  activation: 'relu' # relu, hswish, swish
  MAC_loss: 1 # -1:TDAM(post-quantization), 0:TDAM, 1:TDSS 
  quantizer: 'MG_muldiv_log' # 'MG_divmul_lin', 'MG_muldiv_lin', 'MG_divmul_log', 'MG_muldiv_log', 'LSQ_divmul_lin', 'LSQ_muldiv_lin', 'LSQ_divmul_log', 'LSQ_muldiv_log', 
  n_warpup_epochs: 0
  n_linear_epochs: 0
  base_n_connections: 28218470
  max_scale: 1024
  min_scale: 64
  note: ''